name: Run test and build images
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Build and push the image
        run: |
          docker login --username isaiahdil --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/isaiahdil/demo:latest --file Dockerfile .  
          docker push ghcr.io/isaiahdil/demo:latest